export const TEXT_ES:{[key: string]: string } = {
  primerTitulo: '¡NOS CASAMOS!',
  tNombres: 'Wendy y Christian',
  splashClick: 'Haz clic aquí',
  envelopeFor: 'Para',
  seatReservedSingular: 'asiento reservado',
  seatReservedPlural: 'asientos reservados',
  traduccion: 'Traducir a Inglés',
  pCancion: 'Tu navegador no soporta el elemento de audio.',
  subTitulo: 'You are invited!',
  mensajeBienvenida1: 'Hay momentos en la vida que se vuelven extraordinarios cuando se comparten con quienes amamos.',
  mensajeBienvenida2: 'Por eso, te invitamos a celebrar con nosotros el inicio de este hermoso viaje.',
  mensajeBienvenida3: 'Tu presencia en el día más importante de nuestras vidas será invaluable para nosotros.',
  soloFaltan: 'FALTAN',
  counterDias: 'DIAS',
  counterHoras: 'HORAS',
  counterMinutos: 'MINUTOS',
  counterSeg: 'SEGUNDOS',
  // NOMBRE DE PADRES
  tituloInicialPadres: 'Con la bendición de Dios y nuestros padres',
  subTituloInicialPadres: 'y nuestros padres',
  nomPadresNovia: 'Padres de la novia',
  nomPadresNovio: 'Padres del novio',
  // FECHA Y BODA
  textFechaBoda: 'Nuestra boda será el sábado:',
  fechaBoda: '08 | Marzo | 2025',
  // GUARDAR LA FECHA
  guardaFecha: 'GUARDA LA FECHA',
  // CEREMONIA Y RECEPCIÓN
  tituloCeremonia: 'CEREMONIA Y RECEPCIÓN',
  direccionCeremonia: 'Finca Santa Isabel Antigua Guatemala',
  horaCeremonia: 'Hora: 3:30 Hrs.',
  ubicacion: 'Ver Ubicación',
  tituloRecepcion: 'RECEPCIÓN',
  direccionRecepcion: 'Convento Santa Clara, Antigua Guatemala',
  horaRecepcion: 'Hora: 4:30 Hrs.',
  //ITINERARIO
  tituloItinerario1: 'Itinerario',
  subttuloItinerario: 'de boda',
  itiCeremonia: 'Ceremonia',
  itiCeremoniaHora: '15:00 Hrs. - 23:00 Hrs.',
  itiRecepcion: 'Recepción',
  itiRecepcionHora: '19:00 Hrs.',
  itiBaile: 'Primer Baile',
  itiBaileHora: '06:30 Hrs.',
  itiComida: 'Comida',
  itiComidaHora: '20:30 Hrs.',
  itiPastel: 'Pastel',
  itiPastelHora: '07:00 Hrs.',
  itiFiesta: 'Fiesta',
  itiFiestaHora: '22:00 Hrs.',
  itiDespedida: 'Despedida',
  itiDespedidaHora: '11:00 Hrs.',
  // VESTIMENTA O DRESS CODE
  tituloVestimenta: 'VESTIMENTA',
  textoVestimentaUno: 'Long gown cocktail dress',
  textoVestimentaDos: 'Queremos que cada detalle de nuestra celebración refleje la esencia de este día tan importante. Por ello, les pedimos vestir de manera formal y evitar los colores blanco (y sus tonalidades), rojo y verde en los atuendos. Además, les agradecemos no utilizar corbatas en tonos verde o azul. Su comprensión y cariño harán que este momento sea aún más especial.',
  // NUESTROS MOMENTOS
  tituloMomentos: 'Nuestros Momentos',
  textoMomentos: 'Ayuda a que nuestros recuerdos de este día especial crezcan. Usa el código QR para compartir tus momentos y ser parte de nuestra historia',
  // REGALOS
  tituloRegalo: 'Regalos',
  textoRegaloUno: 'Tu presencia es nuestro mejor regalo, pero si deseas tener un detalle con nosotros, haz clic aquí para ver las opciones',
  subtituloRegalo: 'Lluvia de sobres',
  textoRegaloDos: 'Los obsequios en efectivo siempre son bienvenidos, pero nunca obligatorios. Todo lo que te pedimos es que estés aquí con nosotros.',
  // NO NIÑOS
  tituloKids: 'Solo para adultos',
  textoKids: ' Adoramos a los pequeños, sin embargo esta celebración está destinada solo para adultos.¡Agradecemos su comprensión! <br><br> NO NIÑOS',
  // PASES
  tituloPases: 'PASES',
  textoPasesUno: 'Están reservados para ti',
  textoPasesDos: '2 asientos en tu honor.',
  //CONFIRMACIÓN DE ASISTENCIA
  tituloConfirmacion: 'Confirma tu Asistencia',
  textoConfirmacionUno: 'Por favor, confirma tu asistencia antes posible.',
  textoConfirmacionDos: '',
  textoConfirmacionTres: 'Contacta a los novios.',
  buttonConfirmacion: 'Contacto Diego',
  buttonForms: 'Confirmar',
  // CONFIRMACION
  mensaje_confirmado: 'CONFIRMACIÓN DE ASISTENCIA',
  yaConfirAsistencia: '¡Ya has confirmado tu asistencia!',
  mensajeBienvenidaConfirm: 'Esperamos contar con tu presencia. Por favor confirma tu asistencia antes del ',
  mensajeInvitacionPara: 'Invitación para',
  labelConfirmaAntesDel: 'Confirma antes del',
  labelNombreCompleto: 'Nombre completo',
  placeholderNombreCompleto: 'Ingresa tu nombre',
  errorNombreCompleto: 'Ingresa tu nombre para confirmar tu asistencia',
  helperSeleccionaOpcion: 'Selecciona una opción para continuar',
  helperConfirmarLugares: 'Confirmar lugares',
  helperAvisarNovios: 'Avisar a los novios',
  labelLugaresReservados: 'Lugares reservados',
  labelMesaAsignada: 'Mesa asignada',
  helperAcompanantes: 'Escribe tu nombre y el nombre de tus acompañantes para ayudarnos a recibirlos mejor.',
  cantidadAsistentes: 'El número de asientos reservados para ti es:',
  alertCantidadAsis: 'Cantidad de asistentes',
  alertaPuedesConfirmarHasta: 'Puedes confirmar hasta',
  alertaMinimoConfirmaciones: 'Debes de ingresar al menos un invitado.',
  invitNoEspecificado: 'Nos hemos dado cuenta de que no se especificaron los nombres de tus acompañantes. Te agradeceríamos mucho si pudieras proporcionarnos esta información para poder llevar un mejor control.',
  mesaAsignada: 'Tu lugar está en la mesa número:',
  NombreInvitadoInput: 'Nombre invitado',
  botonConfirmacion: 'Confirmar',
  totalInvitadosConfirmado: 'Asientos reservados:',
  despedidaEsperamosVerte: '¡Te esperamos!',
  acompañantesAgregados: 'Acompañantes Agregados:',
  txtNoAsistencia: 'Lamentamos que no puedas acompañarnos, ¡Esperamos verte muy pronto!',
  debesIngresarInvitados: 'Debes de ingresar al menos un invitado',
  puedesConfirmar: 'Puedes confirmar hasta',
  invitadoConfirmacion: 'Invitado',
  asistentesAgregados: 'Acompañantes agregados:',
  teEsperamos: '¡Te esperamos!',
  asistiras: '¿Podrás asistir?',
  siAsistire: 'Sí asistiré',
  noAsistira: 'No podré asistir',
  estasSeguro: '¿Estas seguro?',
  fechaConfirmacionCaducada: '¡Ya paso la fecha limite para confirmar tu sistencia!',
  fechaConfirmacionCaducadaDos: 'Si gustas puedes comunicarte con los novios.',
  //VENTANA EMERGENTE CONFIRMACION
  confirmAsistenciatitle: '¿Confirmas esta asistencia?',
  opcancelar: 'Cancelar',
  sininvitadostitle: '¿No agregarás invitados?',
  sininvitadostxt: 'Puedes agregar invitados si lo necesitas.',
  txtnoagregare: 'No agregaré',
  txtsiagregare: 'Si agregaré',
  // DESPEDIDA
  tituloDespedida: 'Con amor',
  DespedidaNombres: 'Roberto & Karin',
  // GLASMMY
  textoGlasmmy: 'Created with love by',
  glasmmy: 'GlasmmyDigital'



}
