export const TEXT_EN:{[key: string]: string } = {
  primerTitulo: 'WE MERRIED!',
  tNombres: 'Valeria & Josué',
  splashClick: 'Click here',
  envelopeFor: 'For',
  seatReservedSingular: 'reserved seat',
  seatReservedPlural: 'reserved seats',
  traduccion: 'Translate to Spanish',
  pCancion: 'Your browser does not support the audio element.',
  subTitulo: 'You are invited!',
  mensajeBienvenida1: 'There are moments in life that become extraordinary when shared with those we love.',
  mensajeBienvenida2: 'That is why we invite you to celebrate with us the beginning of this beautiful journey.',
  mensajeBienvenida3: 'Your presence on the most important day of our lives will be invaluable to us.',
  soloFaltan: 'Countdown:',
  counterDias: 'Days',
  counterHoras: 'Hours',
  counterMinutos: 'Minutes',
  counterSeg: 'Seconds',
  //NOMBRE DE PADRES
  tituloInicialPadres: 'With the blessing of God',
  subTituloInicialPadres: 'and our parents',
  nomPadresNovia: 'Parents of the bride',
  nomPadresNovio: 'Parents of the groom',
  //FECHA Y BODA
  textFechaBoda: 'Our wedding will be on Saturday:',
  fechaBoda: '08 | March | 2025',
  //GUARDAR LA FECHA
  guardaFecha: 'Save the date',
  // CEREMONIA Y RECEPCIÓN
  tituloCeremonia: 'CEREMONY AND RECEPTION',
  direccionCeremonia: 'Finca Santa Isabel, Antigua Guatemala',
  horaCeremonia: 'Time: 3:30 P.M.',
  ubicacion: 'See Location',
  tituloRecepcion: 'RECEPTION',
  direccionRecepcion: 'Convento Santa Clara, Antigua Guatemala',
  horaRecepcion: 'Time: 5:00 P.M.',
  //ITINERARIO
  tituloItinerario1: 'TIMELINE',
  subttuloItinerario: 'Wedding',
  itiCeremonia: 'Ceremony',
  itiCeremoniaHora: 'Time: 03:30 P.M.',
  itiRecepcion: 'Reception',
  itiRecepcionHora: 'Time: 05:00 P.M.',
  itiBaile: 'First dance',
  itiBaileHora: 'Time: 06:30 P.M.',
  itiComida: 'Food',
  itiComidaHora: 'Time: 06:45 P.M.',
  itiPastel: 'Cake',
  itiPastelHora: 'Time: 07:00 P.M.',
  itiFiesta: 'Party',
  itiFiestaHora: 'Time: 06:00 P.M.',
  itiDespedida: 'Farewell',
  itiDespedidaHora: 'Time: 11:00 P.M.',
  // VESTIMENTA O DRESS CODE
  tituloVestimenta: 'DRESS CODE',
  textoVestimentaUno: 'Formal Style',
  textoVestimentaDos: 'Please avoid wearing white and its shades in honor of our celebration.',
  // NUESTROS MOMENTOS
  tituloMomentos: 'Our Moments',
  textoMomentos: 'Help our memories of this special day grow. Use the QR code to share your moments and be part of our story.',
  // REGALOS
  tituloRegalo: 'Gifts',
  textoRegaloUno: 'Your presence is our best gift, but if you want to have a detail with us, Click here to see the options.',
  subtituloRegalo: 'Rain of envelopes',
  textoRegaloDos: 'Cash gifts are always welcome, but never obligatory. All we ask is that you be here with us.',
  // NO NIÑOS
  tituloKids: 'Nour Kids',
  textoKids: 'We love children and they always fill our lives with joy. However, on this occasion, we have decided that our wedding will be an adults-only event.',
  // PASES
  tituloPases: 'PASSES',
  textoPasesUno: 'Are reserved for you',
  textoPasesDos: '2 seats in your honor.',
  //CONFIRMACIÓN DE ASISTENCIA
  tituloConfirmacion: 'CONFIRM YOUR ATTENDANCE',
  textoConfirmacionUno: 'Please confirm your',
  textoConfirmacionDos: 'assistance as soon as possible.',
  textoConfirmacionTres: 'Contacta a los novios.',
  buttonConfirmacion: 'WhatsApp',
  buttonForms: 'CONFIRM',
  // CONFIRMACION
  mensaje_confirmado: 'RSVP',
  yaConfirAsistencia: 'You have already confirmed your attendance!',
  mensajeBienvenidaConfirm: 'We hope to have your presence. Please confirm your attendance before ',
  cantidadAsistentes: 'The number of seats that have been reserved for you is: ',
  alertCantidadAsis: 'Number of attendees',
  alertaPuedesConfirmarHasta: 'You can confirm up to',
  alertaMinimoConfirmaciones: 'Please enter at least one guest.',
  invitNoEspecificado: 'We noticed that the names of your guests weren\'t specified. We would greatly appreciate it if you could provide us with this information to help us maintain better control.',
  mesaAsignada: 'Your place is at table number:',
  NombreInvitadoInput: 'Guest name',
  botonConfirmacion: 'Confirm',
  totalInvitadosConfirmado: 'Guest count:',
  despedidaEsperamosVerte: 'We look forward to seeing you!',
  txtNoAsistencia: 'We’re sorry you can’t join us. We hope to see you very soon!',
  acompañantesAgregados: 'Added Companions:',
  totalInvitados: 'Total Guests:',
  debesIngresarInvitados: 'You must enter at least one guest',
  puedesConfirmar: 'You can confirm up to',
  invitadoConfirmacion: 'Guest',
  asistentesAgregados: 'Added companions:',
  teEsperamos: 'We look forward to seeing you!',
  asistiras: 'Can you attend?',
  siAsistire: 'Yes I will attend',
  noAsistira: 'I won´t attend',
  estasSeguro: 'Are you sure?',
  fechaConfirmacionCaducada: 'The deadline to confirm your attendance has passed!',
  fechaConfirmacionCaducadaDos: 'If you like, you can communicate with the couple.',
  // DESPEDIDA
  tituloDespedida: 'With love,',
  DespedidaNombres: 'Dahne and Daniel',
  // GLASMMY
  textoGlasmmy: 'Created with love by',
  glasmmy: 'GlasmmyDigital'

}
